# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplement_recommendation_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1141, 897)
        self.dockWidget = QtWidgets.QDockWidget(Form)
        self.dockWidget.setGeometry(QtCore.QRect(20, 0, 1101, 891))
        self.dockWidget.setStyleSheet("/* QDockWidget 외곽 */\n"
"QDockWidget {\n"
"    background-color: transparent;\n"
"    border: 1px solid #616161;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* 내부 컨텐츠 배경만 (테두리 없음) */\n"
"QDockWidget QWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"    border-radius: 0px; /* 내부는 모서리 둥글지 않게 */\n"
"}\n"
"\n"
"/* 타이틀 바 */\n"
"QDockWidget::title {\n"
"    background-color: #757575;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    height: 30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border: 1px solid #616161;\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    background: transparent;\n"
"    border: 1px solid #616161;\n"
"    icon-size: 35px;               /* 아이콘 자체 크기 */\n"
"    padding: 0px;                  /* 아이콘 여백 */\n"
"    min-width: 25px;               /* 버튼 크기 */\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"}\n"
"\n"
"\n"
"\n"
"QDockWidget::close-button {\n"
"    image: url(C:/intel_training/Ai_supplement/close_icon_off.png);\n"
"}\n"
"\n"
"QDockWidget::float-button {\n"
"    image: url(C:/intel_training/Ai_supplement/restore_icon.png);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover {\n"
"    background-color: #BDBDBD;\n"
"}\n"
"\n"
"QMainWindow mainWindow;\n"
"mainWindow.setWindowIcon(QIcon(C:/intel_training/Ai_supplement/perilla_favicon.png));")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.pushButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(940, 60, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"background-color :#004D40;\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #004D40; /*테두리 추가*/\n"
"color :  #E0F2F1;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"color : #004D40;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(80, 60, 921, 51))
        self.lineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #004D40; /*테두리 추가*/\n"
"color : #F57F17\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    font-weight: bold;  /* 글씨 굵게 */\n"
"    font-size : 16px;\n"
"    color: black;                /* 입력된 텍스트 색상 */\n"
"    font-style: leelawadee UI;\n"
"}\n"
"\n"
"QLineEdit:!focus:empty \n"
"{\n"
"     font-size : 16px;\n"
"    color: gray;                 /* placeholder 텍스트 색상 */\n"
"    font-style: leelawadee UI;\n"
"}\n"
"\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox = QtWidgets.QGroupBox(self.dockWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(80, 130, 921, 281))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #F57F17\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setGeometry(QtCore.QRect(180, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox.setCheckable(True)
        self.checkBox.setChecked(False)
        self.checkBox.setAutoRepeat(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(330, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_2.setCheckable(True)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setAutoRepeat(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(330, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_3.setCheckable(True)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setAutoRepeat(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(480, 130, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_4.setCheckable(True)
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setAutoRepeat(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(330, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_5.setCheckable(True)
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setAutoRepeat(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(180, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_6.setCheckable(True)
        self.checkBox_6.setChecked(False)
        self.checkBox_6.setAutoRepeat(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setGeometry(QtCore.QRect(630, 90, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_7.setCheckable(True)
        self.checkBox_7.setChecked(False)
        self.checkBox_7.setAutoRepeat(False)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setGeometry(QtCore.QRect(630, 130, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_8.setCheckable(True)
        self.checkBox_8.setChecked(False)
        self.checkBox_8.setAutoRepeat(False)
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_9.setGeometry(QtCore.QRect(180, 130, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_9.setCheckable(True)
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setAutoRepeat(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setGeometry(QtCore.QRect(480, 90, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_10.setCheckable(True)
        self.checkBox_10.setChecked(False)
        self.checkBox_10.setAutoRepeat(False)
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_11.setGeometry(QtCore.QRect(630, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_11.setCheckable(True)
        self.checkBox_11.setChecked(False)
        self.checkBox_11.setAutoRepeat(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_12.setGeometry(QtCore.QRect(330, 180, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_12.setCheckable(True)
        self.checkBox_12.setChecked(False)
        self.checkBox_12.setAutoRepeat(False)
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_13.setGeometry(QtCore.QRect(480, 180, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_13.setCheckable(True)
        self.checkBox_13.setChecked(False)
        self.checkBox_13.setAutoRepeat(False)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_14.setGeometry(QtCore.QRect(330, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_14.setCheckable(True)
        self.checkBox_14.setChecked(False)
        self.checkBox_14.setAutoRepeat(False)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_15.setGeometry(QtCore.QRect(480, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_15.setCheckable(True)
        self.checkBox_15.setChecked(False)
        self.checkBox_15.setAutoRepeat(False)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_16.setGeometry(QtCore.QRect(180, 180, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_16.setCheckable(True)
        self.checkBox_16.setChecked(False)
        self.checkBox_16.setAutoRepeat(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_17.setGeometry(QtCore.QRect(180, 220, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_17.setCheckable(True)
        self.checkBox_17.setChecked(False)
        self.checkBox_17.setAutoRepeat(False)
        self.checkBox_17.setObjectName("checkBox_17")
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setGeometry(QtCore.QRect(80, 430, 921, 271))
        self.tabWidget.setStyleSheet("/* QTabWidget 전체 테두리와 모서리 설정 */\n"
"QTabWidget::pane {\n"
"    border: 2px solid #1B5E20;\n"
"    border-radius: 10px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* 탭 버튼 자체 스타일 */\n"
"QTabBar::tab {\n"
"    background: #E8F5E9;\n"
"    color: #1B5E20;\n"
"    padding: 8px 16px;\n"
"    border: 1px solid #1B5E20;\n"
"    border-top-left-radius: 8px;\n"
"    border-top-right-radius: 8px;\n"
"    margin-right: 2px;\n"
"}\n"
"\n"
"/* 선택된 탭 강조 */\n"
"QTabBar::tab:selected {\n"
"    background: #A5D6A7;\n"
"    color: #0D5302;\n"
"}\n"
"\n"
"/* 마우스 호버 시 */\n"
"QTabBar::tab:hover {\n"
"    background: #C8E6C9;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.checkBox_35 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_35.setGeometry(QtCore.QRect(630, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_35.setFont(font)
        self.checkBox_35.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_35.setCheckable(True)
        self.checkBox_35.setChecked(False)
        self.checkBox_35.setAutoRepeat(False)
        self.checkBox_35.setObjectName("checkBox_35")
        self.checkBox_36 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_36.setGeometry(QtCore.QRect(170, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_36.setFont(font)
        self.checkBox_36.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_36.setCheckable(True)
        self.checkBox_36.setChecked(False)
        self.checkBox_36.setAutoRepeat(False)
        self.checkBox_36.setObjectName("checkBox_36")
        self.checkBox_37 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_37.setGeometry(QtCore.QRect(170, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_37.setFont(font)
        self.checkBox_37.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_37.setCheckable(True)
        self.checkBox_37.setChecked(False)
        self.checkBox_37.setAutoRepeat(False)
        self.checkBox_37.setObjectName("checkBox_37")
        self.checkBox_38 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_38.setGeometry(QtCore.QRect(400, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_38.setFont(font)
        self.checkBox_38.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_38.setCheckable(True)
        self.checkBox_38.setChecked(False)
        self.checkBox_38.setAutoRepeat(False)
        self.checkBox_38.setObjectName("checkBox_38")
        self.checkBox_39 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_39.setGeometry(QtCore.QRect(630, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_39.setFont(font)
        self.checkBox_39.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_39.setCheckable(True)
        self.checkBox_39.setChecked(False)
        self.checkBox_39.setAutoRepeat(False)
        self.checkBox_39.setObjectName("checkBox_39")
        self.checkBox_40 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_40.setGeometry(QtCore.QRect(400, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_40.setFont(font)
        self.checkBox_40.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_40.setCheckable(True)
        self.checkBox_40.setChecked(False)
        self.checkBox_40.setAutoRepeat(False)
        self.checkBox_40.setObjectName("checkBox_40")
        self.checkBox_41 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_41.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_41.setFont(font)
        self.checkBox_41.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_41.setCheckable(True)
        self.checkBox_41.setChecked(False)
        self.checkBox_41.setAutoRepeat(False)
        self.checkBox_41.setObjectName("checkBox_41")
        self.checkBox_42 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_42.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_42.setFont(font)
        self.checkBox_42.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_42.setCheckable(True)
        self.checkBox_42.setChecked(False)
        self.checkBox_42.setAutoRepeat(False)
        self.checkBox_42.setObjectName("checkBox_42")
        self.checkBox_43 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_43.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_43.setFont(font)
        self.checkBox_43.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_43.setCheckable(True)
        self.checkBox_43.setChecked(False)
        self.checkBox_43.setAutoRepeat(False)
        self.checkBox_43.setObjectName("checkBox_43")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.checkBox_52 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_52.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_52.setFont(font)
        self.checkBox_52.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_52.setCheckable(True)
        self.checkBox_52.setChecked(False)
        self.checkBox_52.setAutoRepeat(False)
        self.checkBox_52.setObjectName("checkBox_52")
        self.checkBox_50 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_50.setGeometry(QtCore.QRect(630, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_50.setFont(font)
        self.checkBox_50.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_50.setCheckable(True)
        self.checkBox_50.setChecked(False)
        self.checkBox_50.setAutoRepeat(False)
        self.checkBox_50.setObjectName("checkBox_50")
        self.checkBox_51 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_51.setGeometry(QtCore.QRect(170, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_51.setFont(font)
        self.checkBox_51.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_51.setCheckable(True)
        self.checkBox_51.setChecked(False)
        self.checkBox_51.setAutoRepeat(False)
        self.checkBox_51.setObjectName("checkBox_51")
        self.checkBox_47 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_47.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_47.setFont(font)
        self.checkBox_47.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_47.setCheckable(True)
        self.checkBox_47.setChecked(False)
        self.checkBox_47.setAutoRepeat(False)
        self.checkBox_47.setObjectName("checkBox_47")
        self.checkBox_44 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_44.setGeometry(QtCore.QRect(400, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_44.setFont(font)
        self.checkBox_44.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_44.setCheckable(True)
        self.checkBox_44.setChecked(False)
        self.checkBox_44.setAutoRepeat(False)
        self.checkBox_44.setObjectName("checkBox_44")
        self.checkBox_48 = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_48.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_48.setFont(font)
        self.checkBox_48.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_48.setCheckable(True)
        self.checkBox_48.setChecked(False)
        self.checkBox_48.setAutoRepeat(False)
        self.checkBox_48.setObjectName("checkBox_48")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.checkBox_53 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_53.setGeometry(QtCore.QRect(630, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_53.setFont(font)
        self.checkBox_53.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_53.setCheckable(True)
        self.checkBox_53.setChecked(False)
        self.checkBox_53.setAutoRepeat(False)
        self.checkBox_53.setObjectName("checkBox_53")
        self.checkBox_54 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_54.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_54.setFont(font)
        self.checkBox_54.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_54.setCheckable(True)
        self.checkBox_54.setChecked(False)
        self.checkBox_54.setAutoRepeat(False)
        self.checkBox_54.setObjectName("checkBox_54")
        self.checkBox_55 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_55.setGeometry(QtCore.QRect(170, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_55.setFont(font)
        self.checkBox_55.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_55.setCheckable(True)
        self.checkBox_55.setChecked(False)
        self.checkBox_55.setAutoRepeat(False)
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_56 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_56.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_56.setFont(font)
        self.checkBox_56.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_56.setCheckable(True)
        self.checkBox_56.setChecked(False)
        self.checkBox_56.setAutoRepeat(False)
        self.checkBox_56.setObjectName("checkBox_56")
        self.checkBox_57 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_57.setGeometry(QtCore.QRect(400, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_57.setFont(font)
        self.checkBox_57.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_57.setCheckable(True)
        self.checkBox_57.setChecked(False)
        self.checkBox_57.setAutoRepeat(False)
        self.checkBox_57.setObjectName("checkBox_57")
        self.checkBox_58 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_58.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_58.setFont(font)
        self.checkBox_58.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_58.setCheckable(True)
        self.checkBox_58.setChecked(False)
        self.checkBox_58.setAutoRepeat(False)
        self.checkBox_58.setObjectName("checkBox_58")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.checkBox_59 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_59.setGeometry(QtCore.QRect(400, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_59.setFont(font)
        self.checkBox_59.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_59.setCheckable(True)
        self.checkBox_59.setChecked(False)
        self.checkBox_59.setAutoRepeat(False)
        self.checkBox_59.setObjectName("checkBox_59")
        self.checkBox_60 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_60.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_60.setFont(font)
        self.checkBox_60.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_60.setCheckable(True)
        self.checkBox_60.setChecked(False)
        self.checkBox_60.setAutoRepeat(False)
        self.checkBox_60.setObjectName("checkBox_60")
        self.checkBox_61 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_61.setGeometry(QtCore.QRect(630, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_61.setFont(font)
        self.checkBox_61.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_61.setCheckable(True)
        self.checkBox_61.setChecked(False)
        self.checkBox_61.setAutoRepeat(False)
        self.checkBox_61.setObjectName("checkBox_61")
        self.checkBox_62 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_62.setGeometry(QtCore.QRect(170, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_62.setFont(font)
        self.checkBox_62.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_62.setCheckable(True)
        self.checkBox_62.setChecked(False)
        self.checkBox_62.setAutoRepeat(False)
        self.checkBox_62.setObjectName("checkBox_62")
        self.checkBox_64 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_64.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_64.setFont(font)
        self.checkBox_64.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_64.setCheckable(True)
        self.checkBox_64.setChecked(False)
        self.checkBox_64.setAutoRepeat(False)
        self.checkBox_64.setObjectName("checkBox_64")
        self.checkBox_65 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_65.setGeometry(QtCore.QRect(170, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_65.setFont(font)
        self.checkBox_65.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_65.setCheckable(True)
        self.checkBox_65.setChecked(False)
        self.checkBox_65.setAutoRepeat(False)
        self.checkBox_65.setObjectName("checkBox_65")
        self.checkBox_66 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_66.setGeometry(QtCore.QRect(400, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_66.setFont(font)
        self.checkBox_66.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_66.setCheckable(True)
        self.checkBox_66.setChecked(False)
        self.checkBox_66.setAutoRepeat(False)
        self.checkBox_66.setObjectName("checkBox_66")
        self.checkBox_67 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_67.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_67.setFont(font)
        self.checkBox_67.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_67.setCheckable(True)
        self.checkBox_67.setChecked(False)
        self.checkBox_67.setAutoRepeat(False)
        self.checkBox_67.setObjectName("checkBox_67")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.checkBox_69 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_69.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_69.setFont(font)
        self.checkBox_69.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_69.setCheckable(True)
        self.checkBox_69.setChecked(False)
        self.checkBox_69.setAutoRepeat(False)
        self.checkBox_69.setObjectName("checkBox_69")
        self.checkBox_71 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_71.setGeometry(QtCore.QRect(170, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_71.setFont(font)
        self.checkBox_71.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_71.setCheckable(True)
        self.checkBox_71.setChecked(False)
        self.checkBox_71.setAutoRepeat(False)
        self.checkBox_71.setObjectName("checkBox_71")
        self.checkBox_73 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_73.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_73.setFont(font)
        self.checkBox_73.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_73.setCheckable(True)
        self.checkBox_73.setChecked(False)
        self.checkBox_73.setAutoRepeat(False)
        self.checkBox_73.setObjectName("checkBox_73")
        self.checkBox_76 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_76.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_76.setFont(font)
        self.checkBox_76.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_76.setCheckable(True)
        self.checkBox_76.setChecked(False)
        self.checkBox_76.setAutoRepeat(False)
        self.checkBox_76.setObjectName("checkBox_76")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.checkBox_77 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_77.setGeometry(QtCore.QRect(400, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_77.setFont(font)
        self.checkBox_77.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_77.setCheckable(True)
        self.checkBox_77.setChecked(False)
        self.checkBox_77.setAutoRepeat(False)
        self.checkBox_77.setObjectName("checkBox_77")
        self.checkBox_78 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_78.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_78.setFont(font)
        self.checkBox_78.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_78.setCheckable(True)
        self.checkBox_78.setChecked(False)
        self.checkBox_78.setAutoRepeat(False)
        self.checkBox_78.setObjectName("checkBox_78")
        self.checkBox_79 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_79.setGeometry(QtCore.QRect(630, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_79.setFont(font)
        self.checkBox_79.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_79.setCheckable(True)
        self.checkBox_79.setChecked(False)
        self.checkBox_79.setAutoRepeat(False)
        self.checkBox_79.setObjectName("checkBox_79")
        self.checkBox_80 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_80.setGeometry(QtCore.QRect(170, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_80.setFont(font)
        self.checkBox_80.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_80.setCheckable(True)
        self.checkBox_80.setChecked(False)
        self.checkBox_80.setAutoRepeat(False)
        self.checkBox_80.setObjectName("checkBox_80")
        self.checkBox_81 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_81.setGeometry(QtCore.QRect(630, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_81.setFont(font)
        self.checkBox_81.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_81.setCheckable(True)
        self.checkBox_81.setChecked(False)
        self.checkBox_81.setAutoRepeat(False)
        self.checkBox_81.setObjectName("checkBox_81")
        self.checkBox_82 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_82.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_82.setFont(font)
        self.checkBox_82.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_82.setCheckable(True)
        self.checkBox_82.setChecked(False)
        self.checkBox_82.setAutoRepeat(False)
        self.checkBox_82.setObjectName("checkBox_82")
        self.checkBox_83 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_83.setGeometry(QtCore.QRect(170, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_83.setFont(font)
        self.checkBox_83.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_83.setCheckable(True)
        self.checkBox_83.setChecked(False)
        self.checkBox_83.setAutoRepeat(False)
        self.checkBox_83.setObjectName("checkBox_83")
        self.checkBox_84 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_84.setGeometry(QtCore.QRect(400, 170, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_84.setFont(font)
        self.checkBox_84.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_84.setCheckable(True)
        self.checkBox_84.setChecked(False)
        self.checkBox_84.setAutoRepeat(False)
        self.checkBox_84.setObjectName("checkBox_84")
        self.checkBox_85 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_85.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_85.setFont(font)
        self.checkBox_85.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_85.setCheckable(True)
        self.checkBox_85.setChecked(False)
        self.checkBox_85.setAutoRepeat(False)
        self.checkBox_85.setObjectName("checkBox_85")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.checkBox_86 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_86.setGeometry(QtCore.QRect(400, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_86.setFont(font)
        self.checkBox_86.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_86.setCheckable(True)
        self.checkBox_86.setChecked(False)
        self.checkBox_86.setAutoRepeat(False)
        self.checkBox_86.setObjectName("checkBox_86")
        self.checkBox_87 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_87.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_87.setFont(font)
        self.checkBox_87.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_87.setCheckable(True)
        self.checkBox_87.setChecked(False)
        self.checkBox_87.setAutoRepeat(False)
        self.checkBox_87.setObjectName("checkBox_87")
        self.checkBox_89 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_89.setGeometry(QtCore.QRect(170, 100, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_89.setFont(font)
        self.checkBox_89.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_89.setCheckable(True)
        self.checkBox_89.setChecked(False)
        self.checkBox_89.setAutoRepeat(False)
        self.checkBox_89.setObjectName("checkBox_89")
        self.checkBox_91 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_91.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_91.setFont(font)
        self.checkBox_91.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_91.setCheckable(True)
        self.checkBox_91.setChecked(False)
        self.checkBox_91.setAutoRepeat(False)
        self.checkBox_91.setObjectName("checkBox_91")
        self.checkBox_94 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_94.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_94.setFont(font)
        self.checkBox_94.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_94.setCheckable(True)
        self.checkBox_94.setChecked(False)
        self.checkBox_94.setAutoRepeat(False)
        self.checkBox_94.setObjectName("checkBox_94")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.checkBox_95 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_95.setGeometry(QtCore.QRect(400, 100, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_95.setFont(font)
        self.checkBox_95.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_95.setCheckable(True)
        self.checkBox_95.setChecked(False)
        self.checkBox_95.setAutoRepeat(False)
        self.checkBox_95.setObjectName("checkBox_95")
        self.checkBox_96 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_96.setGeometry(QtCore.QRect(170, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_96.setFont(font)
        self.checkBox_96.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_96.setCheckable(True)
        self.checkBox_96.setChecked(False)
        self.checkBox_96.setAutoRepeat(False)
        self.checkBox_96.setObjectName("checkBox_96")
        self.checkBox_98 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_98.setGeometry(QtCore.QRect(170, 100, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_98.setFont(font)
        self.checkBox_98.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_98.setCheckable(True)
        self.checkBox_98.setChecked(False)
        self.checkBox_98.setAutoRepeat(False)
        self.checkBox_98.setObjectName("checkBox_98")
        self.checkBox_100 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_100.setGeometry(QtCore.QRect(630, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_100.setFont(font)
        self.checkBox_100.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_100.setCheckable(True)
        self.checkBox_100.setChecked(False)
        self.checkBox_100.setAutoRepeat(False)
        self.checkBox_100.setObjectName("checkBox_100")
        self.checkBox_103 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_103.setGeometry(QtCore.QRect(400, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(-1)
        self.checkBox_103.setFont(font)
        self.checkBox_103.setStyleSheet("QCheckBox \n"
"{\n"
"    spacing: 3px; /* 체크박스와 텍스트 사이 간격 */\n"
"    font-size: 13px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border: 1.5px solid gray;        /* 기본 테두리 색상 */\n"
"    background-color: white;       /* 기본 배경색 */\n"
"    border-radius: 1px;         /*모서리 둥글게*/\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: white;       /* 체크된 후 바탕색 */\n"
"    border: 1.5px solid red;         /* 체크된 후 테두리 */\n"
"    image: url(C:/intel_training/Ai_supplement/pill.png); /* 체크 표시 이미지 (선택 사항) */\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:hover\n"
"{\n"
"background-color : #E0F2F1;\n"
"\n"
"}\n"
"")
        self.checkBox_103.setCheckable(True)
        self.checkBox_103.setChecked(False)
        self.checkBox_103.setAutoRepeat(False)
        self.checkBox_103.setObjectName("checkBox_103")
        self.tabWidget.addTab(self.tab_8, "")
        self.lineEdit.raise_()
        self.groupBox.raise_()
        self.pushButton.raise_()
        self.tabWidget.raise_()
        self.dockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "검색"))
        self.lineEdit.setPlaceholderText(_translate("Form", "제품 또는 증상을 입력하세요"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">영양제 종류</p><p align=\"center\">(supplements) </p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">비타민 종류</p><p align=\"center\">(vitamins) </p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">미네랄 종류</p><p align=\"center\">(minera) </p></body></html>"))
        self.checkBox.setText(_translate("Form", "비타민"))
        self.checkBox_2.setText(_translate("Form", "미네랄"))
        self.checkBox_3.setText(_translate("Form", "여성용 종합비타민"))
        self.checkBox_4.setText(_translate("Form", "남성용 종합비타민"))
        self.checkBox_5.setText(_translate("Form", "비타민 B"))
        self.checkBox_6.setText(_translate("Form", "비타민 A"))
        self.checkBox_7.setText(_translate("Form", "비타민 D"))
        self.checkBox_8.setText(_translate("Form", "임산부용 종합비타민"))
        self.checkBox_9.setText(_translate("Form", "비타민 E"))
        self.checkBox_10.setText(_translate("Form", "비타민 C"))
        self.checkBox_11.setText(_translate("Form", "철분"))
        self.checkBox_12.setText(_translate("Form", "콜린"))
        self.checkBox_13.setText(_translate("Form", "요오드"))
        self.checkBox_14.setText(_translate("Form", "셀레늄"))
        self.checkBox_15.setText(_translate("Form", "아연"))
        self.checkBox_16.setText(_translate("Form", "칼슘"))
        self.checkBox_17.setText(_translate("Form", "마그네슘"))
        self.checkBox_35.setText(_translate("Form", "생리통"))
        self.checkBox_36.setText(_translate("Form", "성장기"))
        self.checkBox_37.setText(_translate("Form", "근육 경련"))
        self.checkBox_38.setText(_translate("Form", "근육 기능 유지"))
        self.checkBox_39.setText(_translate("Form", "근육 약화 방지"))
        self.checkBox_40.setText(_translate("Form", "부정맥"))
        self.checkBox_41.setText(_translate("Form", "골다공증 예방"))
        self.checkBox_42.setText(_translate("Form", "뼈 통증"))
        self.checkBox_43.setText(_translate("Form", "뼈 건강"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "뼈/근육"))
        self.checkBox_52.setText(_translate("Form", "집중력 향상"))
        self.checkBox_50.setText(_translate("Form", "만성 피로"))
        self.checkBox_51.setText(_translate("Form", " 우울증"))
        self.checkBox_47.setText(_translate("Form", "신경 발달"))
        self.checkBox_44.setText(_translate("Form", "신경통 에너지 대사 저하"))
        self.checkBox_48.setText(_translate("Form", "기억력"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "뇌/신경/정신건강"))
        self.checkBox_53.setText(_translate("Form", "심혈관 기능"))
        self.checkBox_54.setText(_translate("Form", "창백한 피부"))
        self.checkBox_55.setText(_translate("Form", "운동 시 호흡 곤란"))
        self.checkBox_56.setText(_translate("Form", "두통"))
        self.checkBox_57.setText(_translate("Form", "혈액 순환 개선"))
        self.checkBox_58.setText(_translate("Form", "빈혈"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "혈액순환"))
        self.checkBox_59.setText(_translate("Form", "월경 주기 조절"))
        self.checkBox_60.setText(_translate("Form", "갑상선 기능 저하"))
        self.checkBox_61.setText(_translate("Form", "생리전 증후군(PMS)"))
        self.checkBox_62.setText(_translate("Form", "생리 불순"))
        self.checkBox_64.setText(_translate("Form", "추위 민감성"))
        self.checkBox_65.setText(_translate("Form", "생식기능"))
        self.checkBox_66.setText(_translate("Form", "정자 건강"))
        self.checkBox_67.setText(_translate("Form", "체중 증가"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "갑상선/호르몬"))
        self.checkBox_69.setText(_translate("Form", "면역력 저하"))
        self.checkBox_71.setText(_translate("Form", "세포 손상 방지"))
        self.checkBox_73.setText(_translate("Form", "항산화 작용"))
        self.checkBox_76.setText(_translate("Form", "감염 저항성 감소"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "면역력/항산화"))
        self.checkBox_77.setText(_translate("Form", "점막 건조(눈,코,입)"))
        self.checkBox_78.setText(_translate("Form", "피부 트러블"))
        self.checkBox_79.setText(_translate("Form", "입술 갈라짐"))
        self.checkBox_80.setText(_translate("Form", "피부 탄력 저하"))
        self.checkBox_81.setText(_translate("Form", "탈모"))
        self.checkBox_82.setText(_translate("Form", "피부 노화"))
        self.checkBox_83.setText(_translate("Form", "구내염"))
        self.checkBox_84.setText(_translate("Form", "손톱"))
        self.checkBox_85.setText(_translate("Form", "피부 건조"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "피부/모발/손발톱/점막"))
        self.checkBox_86.setText(_translate("Form", "정신적 피로"))
        self.checkBox_87.setText(_translate("Form", "스트레스 완화"))
        self.checkBox_89.setText(_translate("Form", "우울감"))
        self.checkBox_91.setText(_translate("Form", "불면"))
        self.checkBox_94.setText(_translate("Form", "수면 장애"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "수면/스트레스/정신"))
        self.checkBox_95.setText(_translate("Form", "임신 중 필수 비타민"))
        self.checkBox_96.setText(_translate("Form", "태아 뇌"))
        self.checkBox_98.setText(_translate("Form", "임신 중 필수 미네랄"))
        self.checkBox_100.setText(_translate("Form", "산모 건강 유지"))
        self.checkBox_103.setText(_translate("Form", "신경 발달"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Form", "임신/태아"))
