# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'supplement_recommendation_app2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(946, 806)
        self.dockWidget = QtWidgets.QDockWidget(Form)
        self.dockWidget.setGeometry(QtCore.QRect(20, 10, 911, 781))
        self.dockWidget.setStyleSheet("/* QDockWidget 외곽 */\n"
"QDockWidget {\n"
"    background-color: transparent;\n"
"    border: 1px solid #616161;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/* 내부 컨텐츠 배경만 (테두리 없음) */\n"
"QDockWidget QWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"    border-radius: 0px; /* 내부는 모서리 둥글지 않게 */\n"
"}\n"
"\n"
"/* 타이틀 바 */\n"
"QDockWidget::title {\n"
"    background-color: #757575;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    height: 30px;\n"
"    border-top-left-radius: 10px;\n"
"    border-top-right-radius: 10px;\n"
"    border: 1px solid #616161;\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    background: transparent;\n"
"    border: 1px solid #616161;\n"
"    icon-size: 35px;               /* 아이콘 자체 크기 */\n"
"    padding: 0px;                  /* 아이콘 여백 */\n"
"    min-width: 25px;               /* 버튼 크기 */\n"
"    min-height: 25px;\n"
"    max-width: 25px;\n"
"    max-height: 25px;\n"
"}\n"
"\n"
"\n"
"\n"
"QDockWidget::close-button {\n"
"    image: url(C:/intel_training/Ai_supplement/close_icon_off.png);\n"
"}\n"
"\n"
"QDockWidget::float-button {\n"
"    image: url(C:/intel_training/Ai_supplement/restore_icon.png);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover {\n"
"    background-color: #BDBDBD;\n"
"}\n"
"\n"
"QMainWindow mainWindow;\n"
"mainWindow.setWindowIcon(QIcon(C:/intel_training/Ai_supplement/perilla_favicon.png));")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(30, 30, 351, 391))
        self.label.setStyleSheet("QLabel\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #F57F17\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(430, 90, 451, 331))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #F57F17\n"
"}")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.dockWidgetContents)
        self.comboBox.setGeometry(QtCore.QRect(430, 30, 451, 31))
        self.comboBox.setStyleSheet("QComboBox\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #F57F17\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_url = QtWidgets.QPushButton(self.dockWidgetContents)
        self.pushButton_url.setGeometry(QtCore.QRect(230, 450, 341, 31))
        self.pushButton_url.setStyleSheet("QPushButton\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #F57F17\n"
"}")
        self.pushButton_url.setObjectName("pushButton_url")
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(60, 450, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Leelawadee UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(50, 510, 831, 181))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"\n"
"border-radius : 10px; /*모서리 둥글게*/\n"
"padding : 4px; /*내부 여백*/\n"
"border : 2px solid #1B5E20; /*테두리 추가*/\n"
"color : #F57F17\n"
"}")
        self.label_4.setObjectName("label_4")
        self.dockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "제품이미지(없으면 제품이름)"))
        self.label_2.setText(_translate("Form", "영양제 성분"))
        self.comboBox.setItemText(0, _translate("Form", "추천된 제품들"))
        self.comboBox.setItemText(1, _translate("Form", "추가하기"))
        self.pushButton_url.setText(_translate("Form", "url button"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">제품 구매하러 가기</p></body></html>"))
        self.label_4.setText(_translate("Form", "광고 문의 010 - 123 -4567"))
